[project]
name = "llm-qna"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.3.0",
    "bitsandbytes>=0.45.1",
    "halo>=0.0.31",
    "rich>=13.9.4",
    "transformers>=4.48.1",
]
